### ISSUE TITLE
Unnecessary use of Oxford comma.

### ISSUE THREAD

**Issue by yoy333** [oliversiegel/Prank_Game#5]
We are using the oxford comma in a place where it is not needed.

`Copyright by Colin, Quinn, and Joshua.`

Most people argue the oxford comma is useless in most cases, but all agree that the oxford comma is useless in this case.
Please fix this.
It is extremely urgent!
To Do:

- [x] Remove the Oxford comma.

**Comment by oliversiegel** [comment]
I suppose
